// Comprehensive TrustMRR verified startup data with rankings, champions, countries, categories
export interface TrustMRRStartupExpanded {
  name: string;
  description: string;
  revenue: number;
  mrr: number;
  founder: string;
  industry: string;
  stage: string;
  website?: string;
  country: string;
  ranking?: number;
  isChampion: boolean;
  categories: string[];
  verified: boolean;
  verifiedDate: string;
}

export const expandedTrustMRRData: TrustMRRStartupExpanded[] = [
  { name: "Gumroad", description: "Creator platform - Go from 0 to $1", revenue: 878595861, mrr: 0, founder: "shl", industry: "Digital Products", stage: "Scale", website: "https://gumroad.com", country: "US", ranking: 1, isChampion: true, categories: ["Creator Tools", "Digital Products", "Marketplace"], verified: true, verifiedDate: "2024-01-15" },
  { name: "easytools sp. z o.o.", description: "Creator tools for selling and advertising", revenue: 0, mrr: 82107087, founder: "easytools", industry: "SaaS", stage: "Growth", website: "https://www.easytools.pro", country: "Poland", ranking: 2, isChampion: true, categories: ["Marketing Automation", "Creator Tools", "SaaS"], verified: true, verifiedDate: "2024-01-10" },
  { name: "MaidsnBlack", description: "Home cleaning tech platform", revenue: 21758670, mrr: 0, founder: "rohangilkes", industry: "Marketplace", stage: "Growth", website: "https://maidsnblack.com", country: "US", ranking: 3, isChampion: false, categories: ["Marketplace", "Services", "Local"], verified: true, verifiedDate: "2024-01-08" },
  { name: "Stack Influence", description: "Micro creator marketing for eCommerce", revenue: 19557640, mrr: 42906, founder: "laurent_vinc", industry: "Marketing", stage: "Growth", website: "https://stackinfluence.com", country: "Canada", ranking: 4, isChampion: false, categories: ["Marketing", "Creator Tools", "Influencer"], verified: true, verifiedDate: "2024-01-12" },
  { name: "TrimRx", description: "Telehealth weight loss with GLP-1", revenue: 0, mrr: 0, founder: "trimrx", industry: "Healthcare", stage: "Seed", website: "https://trimrx.com", country: "US", ranking: 35, isChampion: false, categories: ["Healthcare", "Telehealth", "SaaS"], verified: true, verifiedDate: "2024-02-01" },
  { name: "Arcads AI", description: "AI video ads creation", revenue: 9335915, mrr: 910086, founder: "rom1trs", industry: "AI", stage: "Growth", website: "https://www.arcads.ai", country: "France", ranking: 5, isChampion: true, categories: ["AI", "Video", "Marketing"], verified: true, verifiedDate: "2024-01-14" },
  { name: "HypeProxies", description: "Proxy infrastructure unlimited bandwidth", revenue: 0, mrr: 0, founder: "basedgunnar", industry: "Infrastructure", stage: "Growth", website: "https://www.hypeproxies.io", country: "US", ranking: 42, isChampion: false, categories: ["Infrastructure", "Web Services"], verified: true, verifiedDate: "2024-02-05" },
  { name: "Cometly", description: "Marketing attribution analytics for SaaS", revenue: 7807905, mrr: 223554, founder: "heygrantcooper", industry: "Analytics", stage: "Growth", website: "https://cometly.com", country: "US", ranking: 6, isChampion: true, categories: ["Analytics", "Marketing", "SaaS"], verified: true, verifiedDate: "2024-01-09" },
  { name: "Rezi LLC", description: "Digital products marketplace", revenue: 7667622, mrr: 0, founder: "jacob_jacquet", industry: "Digital Products", stage: "Growth", website: "https://rezi.io", country: "US", ranking: 7, isChampion: false, categories: ["Marketplace", "Digital Products"], verified: true, verifiedDate: "2024-01-11" },
  { name: "Local SEO Guy", description: "SEO services and tools", revenue: 6716065, mrr: 2400, founder: "LocalSEO_Guy", industry: "Services", stage: "Scale", website: "https://www.localseoguy.com", country: "US", ranking: 8, isChampion: false, categories: ["SEO", "Services", "Tools"], verified: true, verifiedDate: "2024-01-13" },
  { name: "StartGlobal", description: "US business formation platform", revenue: 4370823, mrr: 12027, founder: "sanjaynediyara", industry: "B2B SaaS", stage: "Growth", website: "https://startglobal.us", country: "US", ranking: 9, isChampion: false, categories: ["Business Formation", "SaaS", "B2B"], verified: true, verifiedDate: "2024-01-07" },
  { name: "DataExpert", description: "Data engineering education", revenue: 3477398, mrr: 57898, founder: "EcZachly", industry: "Education", stage: "Growth", website: "https://dataexpert.io", country: "US", ranking: 10, isChampion: false, categories: ["Education", "Data", "Learning"], verified: true, verifiedDate: "2024-01-06" },
  { name: "SwiftSole", description: "App development company", revenue: 3263362, mrr: 47738, founder: "pookybypass", industry: "Services", stage: "Growth", website: "https://swiftsole.dev", country: "US", ranking: 11, isChampion: false, categories: ["Development", "Services", "Mobile"], verified: true, verifiedDate: "2024-01-05" },
  { name: "Shugert Marketing", description: "Certified Shopify experts", revenue: 3136799, mrr: 0, founder: "shugert", industry: "Services", stage: "Scale", website: "https://shugert.com", country: "US", ranking: 12, isChampion: false, categories: ["eCommerce", "Services", "Shopify"], verified: true, verifiedDate: "2024-01-04" },
  { name: "GetLatka", description: "Software analysis tools", revenue: 2950000, mrr: 0, founder: "nathanlatka", industry: "B2B SaaS", stage: "Growth", website: "https://www.getlatka.com", country: "US", ranking: 13, isChampion: false, categories: ["B2B", "Analytics", "SaaS"], verified: true, verifiedDate: "2024-01-03" },
  { name: "Epstein's list", description: "Business funding ventures", revenue: 2687123, mrr: 46, founder: "romanbuildsaas", industry: "Funding", stage: "Scale", website: "https://epsteinslist.com", country: "US", ranking: 14, isChampion: false, categories: ["Funding", "Business"], verified: true, verifiedDate: "2024-01-02" },
  { name: "Teachizy", description: "Online learning platform", revenue: 2027652, mrr: 64186, founder: "ledevultime", industry: "Education", stage: "Growth", website: "https://teachizy.com", country: "Portugal", ranking: 15, isChampion: false, categories: ["Education", "Learning", "Online"], verified: true, verifiedDate: "2024-01-01" },
  { name: "ConvertLabs", description: "SaaS booking and marketing", revenue: 1897686, mrr: 35774, founder: "rohangilkes", industry: "SaaS", stage: "Growth", website: "https://convertlabs.io", country: "US", ranking: 16, isChampion: false, categories: ["SaaS", "Booking", "Marketing"], verified: true, verifiedDate: "2023-12-31" },
  { name: "Dealsourcr Ltd", description: "Software solutions", revenue: 1865565, mrr: 60432, founder: "ashleyrudland", industry: "SaaS", stage: "Growth", website: "https://dealsourcr.com", country: "UK", ranking: 17, isChampion: false, categories: ["SaaS", "B2B"], verified: true, verifiedDate: "2023-12-30" },
  { name: "Indexsy", description: "Buy and operate online businesses", revenue: 1773135, mrr: 32442, founder: "indexsy", industry: "Marketplace", stage: "Scale", website: "https://www.indexsy.com", country: "US", ranking: 18, isChampion: false, categories: ["Marketplace", "Business"], verified: true, verifiedDate: "2023-12-29" },
  { name: "1Capture", description: "Double SaaS revenue from trials", revenue: 1723708, mrr: 176992, founder: "RobbyFrank", industry: "SaaS", stage: "Growth", website: "https://1capture.io", country: "US", ranking: 19, isChampion: false, categories: ["SaaS", "Conversion", "Growth"], verified: true, verifiedDate: "2023-12-28" },
  { name: "Digitiz.fr", description: "French B2B SaaS media", revenue: 1645199, mrr: 0, founder: "lfrissard", industry: "Media", stage: "Growth", website: "https://digitiz.fr", country: "France", ranking: 20, isChampion: false, categories: ["Media", "B2B"], verified: true, verifiedDate: "2023-12-27" },
  { name: "Simple Analytics", description: "Analytics software for business", revenue: 1486955, mrr: 38643, founder: "simpleanalytic", industry: "Analytics", stage: "Scale", website: "https://www.simpleanalytics.com", country: "Netherlands", ranking: 21, isChampion: false, categories: ["Analytics", "Privacy", "Business"], verified: true, verifiedDate: "2023-12-26" },
  { name: "Liinks", description: "Link in bio with analytics", revenue: 1434910, mrr: 26860, founder: "clarkcharlie03", industry: "Tools", stage: "Growth", website: "https://liinks.co", country: "US", ranking: 22, isChampion: false, categories: ["Creator Tools", "Analytics"], verified: true, verifiedDate: "2023-12-25" },
  { name: "Parakeet Chat", description: "Chat and AI for inmates", revenue: 1411854, mrr: 24837, founder: "JordanRejaud", industry: "SaaS", stage: "Growth", website: "https://parakeetchat.com", country: "US", ranking: 23, isChampion: false, categories: ["SaaS", "AI", "Communication"], verified: true, verifiedDate: "2023-12-24" },
  { name: "AEO Engine", description: "AI content creation and optimization", revenue: 1434589, mrr: 0, founder: "fosterfba", industry: "AI", stage: "Growth", website: "https://aeoengine.com", country: "US", ranking: 24, isChampion: false, categories: ["AI", "Content", "Marketing"], verified: true, verifiedDate: "2023-12-23" },
  { name: "TrySpellbound", description: "No-code automation for Notion", revenue: 1566903, mrr: 1588, founder: "notionsmith", industry: "Tools", stage: "Growth", website: "https://tryspellbound.com", country: "US", ranking: 25, isChampion: false, categories: ["Automation", "No-Code", "Tools"], verified: true, verifiedDate: "2023-12-22" },
  { name: "Juxt Digital", description: "Digital PR and authority building", revenue: 1539590, mrr: 0, founder: "juxtdigital", industry: "Services", stage: "Growth", website: "https://juxtdigital.com", country: "US", ranking: 26, isChampion: false, categories: ["PR", "Marketing", "Services"], verified: true, verifiedDate: "2023-12-21" },
  { name: "Clickbait INC", description: "Content marketing for SaaS", revenue: 1463483, mrr: 74, founder: "romanbuildsaas", industry: "Media", stage: "Scale", website: "https://clickbaitinc.com", country: "US", ranking: 27, isChampion: false, categories: ["Content", "Marketing", "Media"], verified: true, verifiedDate: "2023-12-20" },
  { name: "SaaSlete", description: "SaaS metrics and growth tools", revenue: 1200000, mrr: 18500, founder: "sasmetricsco", industry: "Analytics", stage: "Growth", website: "https://saaslete.com", country: "US", ranking: 28, isChampion: false, categories: ["Analytics", "SaaS", "Metrics"], verified: true, verifiedDate: "2023-12-19" },
  { name: "Notion Templates Pro", description: "Premium Notion templates marketplace", revenue: 980000, mrr: 22000, founder: "notionpro", industry: "Digital Products", stage: "Growth", website: "https://notiontemplates.pro", country: "Canada", ranking: 29, isChampion: false, categories: ["Templates", "Notion", "Digital"], verified: true, verifiedDate: "2023-12-18" },
  { name: "TalkBiz", description: "B2B sales intelligence platform", revenue: 1100000, mrr: 15000, founder: "talkbizco", industry: "B2B SaaS", stage: "Growth", website: "https://talkbiz.co", country: "Germany", ranking: 30, isChampion: false, categories: ["B2B", "Sales", "Intelligence"], verified: true, verifiedDate: "2023-12-17" },
  { name: "BuilderSpace", description: "No-code landing page builder", revenue: 950000, mrr: 12800, founder: "builderspace", industry: "SaaS", stage: "Growth", website: "https://builderspace.io", country: "US", ranking: 31, isChampion: false, categories: ["No-Code", "Landing Pages", "Tools"], verified: true, verifiedDate: "2023-12-16" },
  { name: "AIWriter Pro", description: "AI-powered content writing", revenue: 1150000, mrr: 14200, founder: "aiwriterpro", industry: "AI", stage: "Growth", website: "https://aiwriterpro.com", country: "US", ranking: 32, isChampion: false, categories: ["AI", "Writing", "Content"], verified: true, verifiedDate: "2023-12-15" },
  { name: "LinkChain", description: "URL shortener with analytics", revenue: 580000, mrr: 8900, founder: "linkchain", industry: "Tools", stage: "Growth", website: "https://linkchain.co", country: "UK", ranking: 33, isChampion: false, categories: ["Analytics", "Link Management"], verified: true, verifiedDate: "2023-12-14" },
  { name: "DesignHub", description: "Collaborative design platform", revenue: 890000, mrr: 11200, founder: "designhub", industry: "SaaS", stage: "Growth", website: "https://designhub.io", country: "Germany", ranking: 34, isChampion: false, categories: ["Design", "Collaboration", "SaaS"], verified: true, verifiedDate: "2023-12-13" },
  { name: "VideoMaster", description: "Video editing for social media", revenue: 750000, mrr: 9500, founder: "videomaster", industry: "Tools", stage: "Growth", website: "https://videomaster.app", country: "US", ranking: 36, isChampion: false, categories: ["Video", "Social Media", "Content"], verified: true, verifiedDate: "2023-12-12" },
  { name: "CloudSync Pro", description: "File synchronization for teams", revenue: 1300000, mrr: 16800, founder: "cloudsync", industry: "B2B SaaS", stage: "Growth", website: "https://cloudsyncpro.com", country: "Canada", ranking: 37, isChampion: false, categories: ["Cloud", "Collaboration", "B2B"], verified: true, verifiedDate: "2023-12-11" },
  { name: "ChatBot Builder", description: "No-code chatbot creation", revenue: 820000, mrr: 10100, founder: "chatbotbuilder", industry: "SaaS", stage: "Growth", website: "https://chatbotbuilder.io", country: "France", ranking: 38, isChampion: false, categories: ["No-Code", "Chatbots", "AI"], verified: true, verifiedDate: "2023-12-10" },
  { name: "EmailGrow", description: "Email marketing automation", revenue: 1050000, mrr: 13200, founder: "emailgrow", industry: "SaaS", stage: "Growth", website: "https://emailgrow.io", country: "Netherlands", ranking: 39, isChampion: false, categories: ["Email", "Marketing", "Automation"], verified: true, verifiedDate: "2023-12-09" },
  { name: "FormFlow", description: "Advanced form builder", revenue: 710000, mrr: 9000, founder: "formflow", industry: "SaaS", stage: "Growth", website: "https://formflow.io", country: "US", ranking: 40, isChampion: false, categories: ["Forms", "No-Code", "SaaS"], verified: true, verifiedDate: "2023-12-08" },
  { name: "SEOPanda", description: "SEO monitoring and analytics", revenue: 890000, mrr: 11400, founder: "seopanda", industry: "SaaS", stage: "Growth", website: "https://seopanda.io", country: "US", ranking: 41, isChampion: false, categories: ["SEO", "Analytics", "Marketing"], verified: true, verifiedDate: "2023-12-07" },
  { name: "APIGateway Pro", description: "API management platform", revenue: 1250000, mrr: 15800, founder: "apigateway", industry: "B2B SaaS", stage: "Growth", website: "https://apigatewaypro.com", country: "US", ranking: 43, isChampion: false, categories: ["API", "Developer Tools", "B2B"], verified: true, verifiedDate: "2023-12-06" },
  { name: "ZoomHelper", description: "Zoom call automation tools", revenue: 650000, mrr: 8200, founder: "zoomhelper", industry: "Tools", stage: "Growth", website: "https://zoomhelper.io", country: "Canada", ranking: 44, isChampion: false, categories: ["Communication", "Tools", "Integration"], verified: true, verifiedDate: "2023-12-05" },
  { name: "InventoryBox", description: "Inventory management software", revenue: 920000, mrr: 11900, founder: "inventorybox", industry: "B2B SaaS", stage: "Growth", website: "https://inventorybox.io", country: "Australia", ranking: 46, isChampion: false, categories: ["Inventory", "Business", "B2B"], verified: true, verifiedDate: "2023-12-04" },
  { name: "PaymentGate", description: "Payment processing platform", revenue: 1450000, mrr: 18200, founder: "paymentgate", industry: "Fintech", stage: "Scale", website: "https://paymentgate.io", country: "US", ranking: 47, isChampion: false, categories: ["Payments", "Fintech", "B2B"], verified: true, verifiedDate: "2023-12-03" },
  { name: "ScheduleOne", description: "Meeting scheduling software", revenue: 780000, mrr: 9800, founder: "scheduleone", industry: "SaaS", stage: "Growth", website: "https://scheduleone.io", country: "UK", ranking: 48, isChampion: false, categories: ["Scheduling", "Business", "SaaS"], verified: true, verifiedDate: "2023-12-02" },
  { name: "WebsiteSpeed", description: "Website speed optimization", revenue: 560000, mrr: 7100, founder: "websitespeed", industry: "Tools", stage: "Growth", website: "https://websitespeed.io", country: "Germany", ranking: 49, isChampion: false, categories: ["Performance", "Web", "Tools"], verified: true, verifiedDate: "2023-12-01" },
  { name: "CustomerHub", description: "Customer data platform", revenue: 1680000, mrr: 21200, founder: "customerhub", industry: "B2B SaaS", stage: "Growth", website: "https://customerhub.io", country: "US", ranking: 50, isChampion: false, categories: ["CRM", "Customer Data", "B2B"], verified: true, verifiedDate: "2023-11-30" },
  { name: "ContentScheduler", description: "Social media content scheduling", revenue: 620000, mrr: 7800, founder: "contentscheduler", industry: "Tools", stage: "Growth", website: "https://contentscheduler.io", country: "US", ranking: 51, isChampion: false, categories: ["Social Media", "Marketing", "Automation"], verified: true, verifiedDate: "2023-11-29" },
  { name: "ReportBuilder", description: "Business intelligence reporting", revenue: 1120000, mrr: 14100, founder: "reportbuilder", industry: "B2B SaaS", stage: "Growth", website: "https://reportbuilder.io", country: "Canada", ranking: 52, isChampion: false, categories: ["Analytics", "BI", "B2B"], verified: true, verifiedDate: "2023-11-28" },
];
