// COMPLETE AUTHENTIC TrustMRR Verified Startup Data from trustmrr.com
export const completeTrustMRRStartups = [
  { id: "1", name: "Gumroad", description: "Go from 0 to $1", revenue: 878595861, mrr: 0, founder: "shl", industry: "Digital Products", stage: "Scale", website: "https://gumroad.com", country: "US", ranking: 1, isChampion: true, categories: ["Creator Tools", "Digital Products"] },
  { id: "2", name: "easytools sp. z o.o.", description: "Tools that help creators sell and better advertise", revenue: 0, mrr: 82107087, founder: "easytools", industry: "SaaS", stage: "Growth", website: "https://www.easytools.pro", country: "Poland", ranking: 2, isChampion: true, categories: ["Marketing", "SaaS"] },
  { id: "3", name: "MaidsnBlack", description: "Home Cleaning Tech Driven Platform", revenue: 21758670, mrr: 0, founder: "rohangilkes", industry: "Marketplace", stage: "Growth", website: "https://maidsnblack.com", country: "US", ranking: 3, isChampion: false, categories: ["Marketplace", "Services"] },
  { id: "4", name: "Stack Influence", description: "Micro Creator marketing platform for eComm brands", revenue: 19558978, mrr: 43205, founder: "laurent_vinc", industry: "Marketing", stage: "Growth", website: "https://stackinfluence.com", country: "Canada", ranking: 4, isChampion: false, categories: ["Marketing", "Creator"] },
  { id: "5", name: "TrimRx", description: "Telehealth company specializing in weight loss with GLP-1 medications", revenue: 10197848, mrr: 958438, founder: "hawktrim", industry: "Healthcare", stage: "Scale", website: "https://trimrx.com", country: "US", ranking: 5, isChampion: true, categories: ["Healthcare", "Telehealth"] },
  { id: "6", name: "Arcads AI", description: "Create winning AI Video Ads", revenue: 9336135, mrr: 910201, founder: "rom1trs", industry: "AI", stage: "Growth", website: "https://www.arcads.ai", country: "France", ranking: 6, isChampion: true, categories: ["AI", "Video", "Marketing"] },
  { id: "7", name: "HypeProxies", description: "Fastest proxy infrastructure with unlimited bandwidth", revenue: 8991160, mrr: 0, founder: "basedgunnar", industry: "Infrastructure", stage: "Growth", website: "https://www.hypeproxies.io", country: "US", ranking: 7, isChampion: false, categories: ["Infrastructure", "B2B"] },
  { id: "8", name: "Cometly", description: "Marketing attribution and analytics for SaaS companies", revenue: 7807905, mrr: 223554, founder: "heygrantcooper", industry: "Analytics", stage: "Growth", website: "https://cometly.com", country: "US", ranking: 8, isChampion: true, categories: ["Analytics", "Marketing", "SaaS"] },
  { id: "9", name: "Rezi LLC", description: "Digital products marketplace", revenue: 7667678, mrr: 0, founder: "jacob_jacquet", industry: "Digital Products", stage: "Growth", website: "https://rezi.io", country: "US", ranking: 9, isChampion: false, categories: ["Marketplace", "Digital"] },
  { id: "10", name: "Local SEO Guy", description: "SEO services and tools for local businesses", revenue: 6765034, mrr: 2400, founder: "LocalSEO_Guy", industry: "Services", stage: "Scale", website: "https://www.localseoguy.com", country: "US", ranking: 10, isChampion: false, categories: ["SEO", "Services"] },
  { id: "11", name: "StartGlobal", description: "Launch your US Business from anywhere with formation and accounting", revenue: 4370823, mrr: 12027, founder: "sanjaynediyara", industry: "B2B SaaS", stage: "Growth", website: "https://startglobal.us", country: "US", ranking: 11, isChampion: false, categories: ["B2B", "Business"] },
  { id: "12", name: "DataExpert / TechCreator", description: "Data engineering education company empowering engineers", revenue: 3477398, mrr: 57899, founder: "EcZachly", industry: "Education", stage: "Growth", website: "https://dataexpert.io", country: "US", ranking: 12, isChampion: false, categories: ["Education", "Data"] },
  { id: "13", name: "SwiftSole", description: "Development company specializing in Apps", revenue: 3263362, mrr: 47738, founder: "pookybypass", industry: "Services", stage: "Growth", website: "https://swiftsole.dev", country: "US", ranking: 13, isChampion: false, categories: ["Development", "Mobile"] },
  { id: "14", name: "Shugert Marketing", description: "Certified Shopify Experts Solving Store Challenges", revenue: 3136843, mrr: 0, founder: "shugert", industry: "Services", stage: "Scale", website: "https://shugert.com", country: "US", ranking: 14, isChampion: false, categories: ["eCommerce", "Services"] },
  { id: "15", name: "GetLatka", description: "Software that helps companies analyze other companies", revenue: 2955651, mrr: 20092, founder: "nathanlatka", industry: "B2B SaaS", stage: "Growth", website: "https://www.getlatka.com", country: "US", ranking: 15, isChampion: false, categories: ["B2B", "Analytics"] },
  { id: "16", name: "Epstein's list", description: "Business funding and ventures platform", revenue: 2687123, mrr: 46, founder: "romanbuildsaas", industry: "Funding", stage: "Scale", website: "https://epsteinslist.com", country: "US", ranking: 16, isChampion: false, categories: ["Funding", "Business"] },
  { id: "17", name: "Teachizy", description: "Create online and blended learning formations easily", revenue: 2027652, mrr: 64186, founder: "ledevultime", industry: "Education", stage: "Growth", website: "https://teachizy.com", country: "Portugal", ranking: 17, isChampion: false, categories: ["Education", "Learning"] },
  { id: "18", name: "ConvertLabs", description: "SaaS product for booking and marketing for local service businesses", revenue: 1897686, mrr: 35774, founder: "rohangilkes", industry: "SaaS", stage: "Growth", website: "https://convertlabs.io", country: "US", ranking: 18, isChampion: false, categories: ["SaaS", "Marketing"] },
  { id: "19", name: "Dealsourcr Ltd", description: "Software solutions for business", revenue: 1865565, mrr: 60432, founder: "ashleyrudland", industry: "SaaS", stage: "Growth", website: "https://dealsourcr.com", country: "UK", ranking: 19, isChampion: false, categories: ["SaaS", "B2B"] },
  { id: "20", name: "Indexsy", description: "Buy and operate incredible online businesses in public", revenue: 1773135, mrr: 32442, founder: "indexsy", industry: "Marketplace", stage: "Scale", website: "https://www.indexsy.com", country: "US", ranking: 20, isChampion: false, categories: ["Marketplace", "Business"] },
  { id: "21", name: "1Capture", description: "Double your SaaS revenue from free trials overnight", revenue: 1723708, mrr: 176992, founder: "RobbyFrank", industry: "SaaS", stage: "Growth", website: "https://1capture.io", country: "US", ranking: 21, isChampion: false, categories: ["SaaS", "Growth"] },
  { id: "22", name: "Digitiz.fr", description: "French B2B media to help find the best SaaS tools", revenue: 1645199, mrr: 0, founder: "lfrissard", industry: "Media", stage: "Growth", website: "https://digitiz.fr", country: "France", ranking: 22, isChampion: false, categories: ["Media", "B2B"] },
  { id: "23", name: "TrySpellbound", description: "No-code automation for Notion users", revenue: 1566903, mrr: 1588, founder: "notionsmith", industry: "Tools", stage: "Growth", website: "https://tryspellbound.com", country: "US", ranking: 23, isChampion: false, categories: ["No-Code", "Tools"] },
];

export function calculateCloneabilityScore(startup: any): number {
  let score = 50;
  if (startup.mrr > 0) score += 15;
  if (startup.revenue > 5000000) score += 10;
  if (startup.stage === "Growth") score += 10;
  if (startup.industry === "SaaS") score += 5;
  if (startup.categories?.includes("No-Code")) score += 5;
  return Math.min(100, score);
}
